
[CourseMenu]
  [CourseTab header:'MAA3'
          tabId:0 /]

  [CourseTab header:'1. Kolmio'
          tabId:1 /]

[/CourseMenu]

[CourseSection sectionId:0]
  [Chapter header:'Luvun tavoitteet']
    // Olen kommentti

    Tässä ensimmäinen kuva, joka on lisätty idyllillä.

    [MaterialPicture imagesrc:'/img/may1/rationaaliK1.png' alt:'kuva1' /]
    Tässä toinen kuva.

    [MaterialPicture imagesrc:'/img/may1/rationaaliK1.png' alt:'kuva2' /]


  [/Chapter]
[/CourseSection]

[CourseSection sectionId:1]
  [Chapter header:'Sama vanha: Luvun tavoitteet']

    Tässä ensimmäinen kuva, joka on lisätty idyllillä.

    [MaterialPicture imagesrc:'/img/may1/rationaaliK1.png' alt:'kuva1' /]

    Tässä toinen kuva.

    [MaterialPicture imagesrc:'/img/may1/rationaaliK1.png' alt:'kuva2' /]

  [/Chapter]

[/CourseSection]
