FROM cypress/browsers:chrome67

ENV YARN_CACHE_FOLDER=/dev/shm/yarn-cache

WORKDIR /app

COPY package-lock.json package.json /app/

COPY . /app/

RUN apt-get install netcat

RUN sh ./scripts/waitForServer.sh

RUN npm install
RUN npm install -g typescript tslint
