[CourseNumberer]
[CourseSection header:'MAA4']
[Chapter header:'Luvun tavoitteet']
[Math] 
1 \ \% = 
\frac {1}{100} = 0{,}01.
[/Math]
[/Chapter]
[/CourseSection]

[CourseSection header:'Vektorit ja xy-koordinaatisto']
[Chapter header:'v2: Luvun tavoitteet']
// Olen kommentti
Tässä tavoitteet2.
[/Chapter]
[/CourseSection]
[/CourseNumberer]