[CourseNumberer]
[CourseMenu]
[CourseTab header:'MAA4' /]

[CourseTab header:'1. Vektorit ja xy-koordinaatisto' /]

[/CourseMenu]

[CourseSection]
[Chapter header:'Luvun tavoitteet']
// Olen kommentti
Tässä tavoitteet.
[/Chapter]
[/CourseSection]

[CourseSection]
[Chapter header:'v2: Luvun tavoitteet']
// Olen kommentti
Tässä tavoitteet2.
[/Chapter]
[/CourseSection]
[/CourseNumberer]