[CourseNumberer]
[CourseSection header:'MAA5']

[Chapter header:'Luvun tavoitteet']
Tässä tavoitteet.

Tässä tavoitteet.
[/Chapter]

[/CourseSection]

[CourseSection header:'Etäisyys']

[Chapter header:'v2: Luvun tavoitteet']
Tässä tavoitteet (v2).

Tässä tavoitteet (v2).
[/Chapter]
[/CourseSection]
[/CourseNumberer]