[CourseNumberer]
[CourseMenu]
[CourseTab header:'MAA5' /]

[CourseTab header:'Etäisyys' /]

[/CourseMenu]

[CourseSection]

[Chapter header:'Luvun tavoitteet']
Tässä tavoitteet.

Tässä tavoitteet.
[/Chapter]

[/CourseSection]

[CourseSection]

[Chapter header:'v2: Luvun tavoitteet']
Tässä tavoitteet (v2).

Tässä tavoitteet (v2).
[/Chapter]
[/CourseSection]
[/CourseNumberer]