[CourseNumberer]
[CourseMenu]
[CourseTab header:'MAA5' /]

[CourseTab header:'Muutos' /]

[/CourseMenu]

[CourseSection]

[Chapter header:'Luvun tavoitteet (uusi versio)']
Tässä tavoitteet ja vähän extra tekstiä.
[/Chapter]

[/CourseSection]

[CourseSection]

[Chapter header:'Matematiikka']
voit muuttaa muuttujan arvoa
[/Chapter]

[/CourseSection]
[/CourseNumberer]