[CourseNumberer]
[CourseMenu]
[CourseTab header:'MAA3' /]

[CourseTab header:'1. Kolmio' /]

[CourseTab header:'2. Tasogeometriaa' /]

[CourseTab header:'3. Avaruusgeometriaa' /]

[/CourseMenu]


[CourseSection]
[Chapter header:'Kurssin tavoitteet ja keskeiset sisällöt']
// Kommentteja voi lisätä materiaalin koodin sekaan selkeyttämään
### Kurssin tavoitteena on, että

* harjaannut hahmottamaan ja kuvaamaan tilaa sekä muotoa koskevaa tietoa sekä kaksi- että kolmiulotteisissa tilanteissa
* harjaannut muotoilemaan, perustelemaan ja käyttämään geometrista tietoa käsitteleviä lauseita
* osaat ratkaista geometrisia ongelmia käyttäen hyväksi kuvioiden ja kappaleiden ominaisuuksia, yhdenmuotoisuutta, Pythagoraan lausetta sekä suora- ja vinokulmaisen kolmion trigonometriaa
* osaat käyttää teknisiä apuvälineitä kuvioiden ja kappaleiden tutkimisessa ja geometriaan liittyvien sovellusongelmien ratkaisussa.

### KESKEISET SISÄLLÖT

* kuvioiden ja kappaleiden yhdenmuotoisuus
* sini- ja kosinilause
* ympyrän, sen osien ja siihen liittyvien suorien geometria
* kuvioihin ja kappaleisiin liittyvien pituuksien, kulmien, pinta-alojen ja tilavuuksien laskeminen

[/Chapter]

[Chapter header:'Opiskeluohjeita']

Kurssimateriaali on jaettu kolmeen lukuun: Kolmio, Tasogeometriaa ja Avaruusgeometriaa.

Pääajatus kurssimateriaalissa on, että matematiikkaa oppii parhaiten tekemällä matematiikkaa. 
Materiaali on tämän vuoksi kirjoitettu niin, että teet tehtäviä käytännössä koko ajan. 
Jokainen luku sisältää kolme eri tehtäväsarjaa. Ensimmäisen tehtäväsarjan tehtävät ovat teorian seassa. 
Tarkoitus on, että etenet materiaalissa tekemällä jokaisen näistä tehtävistä. 
Voit hyvin tehdä tehtäviä yhdessä kaverin kanssa ja voit kysyä opettajalta heti, jos et ymmärrä jotain asiaa. 
Asia voi olla jokin tietty tehtävä, teoriassa oleva virke tai esimerkiksi vieras matemaattinen symboli. 
Pääasia on, että sinä itse teet tehtävät ja ymmärrät, mitä teet. 
Tämän tehtäväsarjan jälkeen kyseisen luvun teoria on käsitelty ja on aika harjoitella ja syventää juuri opittua. 
Ennen tätä opettaja pitää ehkä yhteisen opetustuokion tai -keskustelun, jossa pohditaan yhdessä luvun keskeisiä asioita tai 
työskentelyssä esiin tulleita haastavia kohtia. Mahdollisen opetustuokion jälkeen jatka harjoittelua luvun
lopussa olevien kahden tehtäväsarjan tehtävien avulla. Luonnollisesti mitä enemmän harjoittelet, sitä paremmaksi tulet. 
Kun olet valmis, tee luvun lopussa oleva(t) itsearviointitesti(t). Niiden tarkoitus on kertoa sinulle, oletko ymmärtänyt 
luvun olennaiset asiat ja kehittää samalla oman oppimisesi arviointia, joka on tärkeä tulevaisuuden taito. 
Testeissä pärjääminen ei vielä tarkoita, että osaat luvun asiat esimerkiksi kiitettävällä tasolla, vaan testit 
eskittyvät vahvan perusosaamisen tutkimiseen. Ennen siirtymistä seuraavaan lukuun opettaja haluaa ehkä vielä koota luvussa 
opittuja asioita sekä antaa palautetta oppimisesta ja sen etenemisestä yhteisessä opetuskeskustelussa.
[/Chapter]

[/CourseSection]

[CourseSection]
[Chapter header:'LUVUN TAVOITTEET'] 
// Kommentteja voi lisätä materiaalin koodin sekaan selkeyttämään
[Definition header:'']
Tämän luvun tavoitteena on, että osaat ratkaista erilaisia geometrisia ongelmia kolmioiden avulla. Osaat

* laskea kolmion pinta-alan
* tunnistaa vierus- ja ristikulmat sekä samankohtaiset kulmat ja päätellä niiden suuruud
* perustella kolmioiden yhdenmuotoisuuden ja hyödyntää sitä geometristen ongelmien ratkaisussa
* määrittää kolmioiden sivujen pituuksia ja kulmien suuruuksia Pythagoraan lauseen, trigonometristen suhteiden sekä sini- ja kosinilauseiden avulla
* päätellä suplementtikulman sinin ja kosinin arvot.
[/Definition]
[/Chapter]

[Chapter header:'KOLMION PINTA-ALA JA KULMAT'] 
// Kommentteja voi lisätä materiaalin koodin sekaan selkeyttämään
Kolmioita voidaan käyttää apuna monien geometristen ongelmien ratkaisemisessa. 
Aloitammekin tämän kurssin palauttamalla mieleen kolmioiden geometrisia ominaisuuksia.

Kolmioiden ja muiden tasokuvioiden pinta-alan laskemiseksi tarvitaan sopimus siitä, mitä pinta-alalla tarkoitetaan. 
Lähtökohdaksi voidaan ottaa suorakulmion pinta-ala. Sovitaan siis ensin, mitä suorakulmion pinta-alalla tarkoitetaan. 
Asetetaan seuraava määritelmä:

[Definition header:'MÄÄRITELMÄ: SUORAKULMION PINTA-ALA']
Suorakulmion *pinta-ala* on samasta kärjestä alkavien sivujen pituuksien tulo eli alla olevan kuvion merkinnöillä ab. 
[MaterialPicture imagesrc:'/img/maa3/suoraK04.png' /]
[/Definition]

[Exercise header:'SUORAKULMION PINTA-ALA' open:false]
Kansainvälisissä aikuisten jalkapallo-otteluissa kentän leveyden on oltava vähintään 64 m ja enintään 75 m. 
Kentän pituuden on oltava vähintään 100 m ja enintään 110 m.

(a) Laske suurimman ja pienimmän mahdollisen jalkapallokentän pinta-alojen erotus.

(b) Kuinka monta prosenttia suurin mahdollinen kenttä on isompi kuin pienin mahdollinen kenttä?

[Answer]
(a) [Equation]1850 m^2[/Equation]

(b) [Equation]Noin 29 %.[/Equation]

[/Answer]
[/Exercise]

Suorakulmion pinta-alan avulla saadaan johdettua lauseke kolmion pinta-alalle.

[Exercise header:'KOLMION PINTA-ALA' open:false]

[MaterialPicture imagesrc:'/img/maa3/suoraK17.png' /]
(a) Piirrä yllä olevan kuvan kolmio vihkoosi ja täydennä se suorakulmioksi.

(b) Muodosta suorakulmion pinta-alan lauseke.

(c) Päättele kolmion pinta-ala.

[/Exercise]

[Exercise header:'KOLMION PINTA-ALA' open:false]
[MaterialPicture imagesrc:'/img/maa3/suoraK05.png' /]
(a) Piirrä yllä olevan kuvan kolmio vihkoosi ja täydennä se suorakulmioksi. 
Vinkki: voit esimerkiksi soveltaa edellisen tehtävän ideaa kumpaankin kuvassa näkyvään suorakulmaiseen kolmioon.

(b) Muodosta suorakulmion pinta-alan lauseke.

(c) Päättele kolmion pinta-ala.

[/Exercise]

Edellisten tehtävien tulokset ovat osa seuraavaa teoreemaa. 
Lue teoreema ja sen perustelu huolellisesti. Mieti jokaisen virkkeen jälkeen, mitä järkeä selityksessä on. 
Jos jokin kohta tuntuu hämärältä, keskustele siitä kaverin tai opettajan kanssa.

[Theorem header:'KOLMION PINTA-ALA (TEOREEMA 1)']
Kolmion pinta-ala on puolet sen kannan ja korkeuden tulosta eli alla olevan kuvion merkinnöillä
[Equation]ah/2[/Equation]
[MaterialPicture imagesrc:'/img/maa3/suoraK05.png' /]
[/Theorem]
[Rationalization]
Perustelu: Kolmion korkeusjanan toinen päätepiste voi sijaita kolmion sivun päätepisteessä, kolmion sivulla tai sivun jatkeella. 
Tarkastellaan jokainen näistä tapauksista erikseen.

1. Tapaus, jossa kolmion korkeusjanan toinen päätepiste sijaitsee kolmion sivun päätepisteessä, on käsitelty tehtävässä 1.2. 
[MaterialPicture imagesrc:'/img/maa3/suoraK18.png' /]

2. Tapaus, jossa kolmion korkeusjanan toinen päätepiste sijaitsee kolmion sivulla, on käsitelty tehtävässä 1.3. 
[MaterialPicture imagesrc:'/img/maa3/suoraK05.png' /]

3. Jos kolmion korkeusjanan toinen päätepiste sijaitsee kolmion sivun jatkeella, 
voidaan kolmio täydentää suorakulmaiseksi kolmioksi, jonka pinta-ala on tehtävän 1.2 nojalla 
[Equation](a+x)h/2[/Equation]
[MaterialPicture imagesrc:'/img/maa3/suoraK08.png' /]

Alkuperäisen kolmion pinta-ala saadaan tästä vähentämällä pienemmän suorakulmaisen kolmion pinta-ala: 
[Equation](a+x)h/2 - x/h = (ah+xh-xh)/2 = ah/2 [/Equation]
[/Rationalization]
[/Chapter]
[/CourseSection]
[/CourseNumberer]