[CourseNumberer]
[CourseMenu]
[CourseTab header:'MAA7' /]

[CourseTab header:'Trigonometriaa yksikköympyrässä' /]
[/CourseMenu]

[CourseSection]

[Chapter header:'Luvun tavoitteet']
Tässä tavoitteet.

[Exercise UUID:'12a9cc88-3b49-11e9-a38a-09f848b19644' header:'Tehtävä 1']
erittäin vaikea tehtävä

[Answer]
ei ole mahdollinen ratkaista
[/Answer]
[/Exercise]
[/Chapter]

[/CourseSection]

[CourseSection]

[Chapter header:'v2: Luvun tavoitteet']
Tässä tavoitteet (v2).
[/Chapter]

[/CourseSection]
[/CourseNumberer]