[CourseNumberer]
[CourseMenu]
[CourseTab header:'MAA6' /]

[CourseTab header:'1. Derivaatta' /]

[/CourseMenu]

[CourseSection]
[Chapter header:'Luvun tavoitteet']
Tässä tavoitteet.
[/Chapter]

[/CourseSection]

[CourseSection]
[Chapter header:'v2: Luvun tavoitteet']
Tässä tavoitteet (v2).
[/Chapter]

[/CourseSection]
[/CourseNumberer] 
