[CourseNumberer]
[CourseMenu]
[CourseTab header:'MAY1' /]
[CourseTab header:'uusi tabi' /]
[/CourseMenu]

[CourseSection]
[Chapter header:'Luonnolliset luvut ja kokonaisluvut']
[Exercise header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[Theorem header:'heeteri' /]
[Answer]
kaikki vastaukset ovat oikein
[/Answer]
[Exercise header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[/Chapter]
[Chapter header:'Toka chapteri']
[Exercise header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[Theorem header:'heeteri' /]
[Answer]
kaikki vastaukset ovat oikein
[/Answer]
[/Chapter]
[/CourseSection]

[CourseSection]
[Chapter header:'Luonnolliset luvut ja kokonaisluvut']
[Exercise header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[Theorem header:'heeteri' /]
[Answer]
kaikki vastaukset ovat oikein
[/Answer]
[Exercise header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[/Chapter]
[Chapter header:'Toka chapteri']
[Exercise header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[Theorem header:'heeteri' /]
[Answer]
kaikki vastaukset ovat oikein
[/Answer]
[/Chapter]
[/CourseSection]
[/CourseNumberer]
