[CourseNumberer]
[CourseMenu]
[CourseTab header:'MAY1' /]
[CourseTab header:'uusi tabi' /]
[/CourseMenu]

[CourseSection]
[Chapter header:'Luonnolliset luvut ja kokonaisluvut']
[Exercise UID:'12a9f390-3b49-11e9-a38a-09f848b19644' header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[Theorem header:'heeteri' /]
[Answer]
kaikki vastaukset ovat oikein
[/Answer]
[Exercise UID:'12a9f391-3b49-11e9-a38a-09f848b19644' header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[/Chapter]
[Chapter header:'Toka chapteri']
[Exercise UID:'12a9f392-3b49-11e9-a38a-09f848b19644' header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[Theorem header:'heeteri' /]
[Answer]
kaikki vastaukset ovat oikein
[/Answer]
[/Chapter]
[/CourseSection]

[CourseSection]
[Chapter header:'Luonnolliset luvut ja kokonaisluvut']
[Exercise UID:'12a9f393-3b49-11e9-a38a-09f848b19644' header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[Theorem header:'heeteri' /]
[Answer]
kaikki vastaukset ovat oikein
[/Answer]
[Exercise UID:'12a9f394-3b49-11e9-a38a-09f848b19644' header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[/Chapter]
[Chapter header:'Toka chapteri']
[Exercise UID:'12a9f395-3b49-11e9-a38a-09f848b19644' header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[Theorem header:'heeteri' /]
[Answer]
kaikki vastaukset ovat oikein
[/Answer]
[/Chapter]
[/CourseSection]
[/CourseNumberer]
