[CourseNumberer]
[CourseMenu]
[CourseTab header:'MAY1' /]
[CourseTab header:'uusi tabi' /]
[/CourseMenu]

[CourseSection]
[Chapter header:'Luonnolliset luvut ja kokonaisluvut']
[Exercise UID:57f70b50-3b3e-11e9-a280-e1fede715c08 header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[Theorem header:'heeteri' /]
[Answer]
kaikki vastaukset ovat oikein
[/Answer]
[Exercise UID:57f73260-3b3e-11e9-a280-e1fede715c08 header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[/Chapter]
[Chapter header:'Toka chapteri']
[Exercise UID:57f73261-3b3e-11e9-a280-e1fede715c08 header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[Theorem header:'heeteri' /]
[Answer]
kaikki vastaukset ovat oikein
[/Answer]
[/Chapter]
[/CourseSection]

[CourseSection]
[Chapter header:'Luonnolliset luvut ja kokonaisluvut']
[Exercise UID:57f73262-3b3e-11e9-a280-e1fede715c08 header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[Theorem header:'heeteri' /]
[Answer]
kaikki vastaukset ovat oikein
[/Answer]
[Exercise UID:57f73263-3b3e-11e9-a280-e1fede715c08 header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[/Chapter]
[Chapter header:'Toka chapteri']
[Exercise UID:57f73264-3b3e-11e9-a280-e1fede715c08 header:'Helppo tehtävä (auki)' open:true]
liian helppo tehtävä

[/Exercise]
[Theorem header:'heeteri' /]
[Answer]
kaikki vastaukset ovat oikein
[/Answer]
[/Chapter]
[/CourseSection]
[/CourseNumberer]
