[CourseNumberer]
[CourseSection header:'MAA3']

//Chapter...........................................................
[Chapter header:'Otsikko']
Sisältö...



[/Chapter]


//Chapter with definition...........................................
[Chapter header:'Chapter with Definition']
Sisältö...

[Definition header:'MÄÄRITELMÄ: Esimerkkimääritelmä']
Määritelmän sisältö tulee tähän...
[/Definition]

[/Chapter]

//Chapter with image................................................
[Chapter header:'Chapter with Image']
[Picture imagesrc:'/img/maa3/suoraK17.png' /]
[/Chapter]

//Chapter with exercise and answer..................................
[Chapter header:'Chapter with exercise and answer']
[Exercise UUID:'12a9cc83-3b49-11e9-a38a-09f848b19644' header:'Tehtävän otsikko' open:false]
Tehtävän ohjeistus ja vastausvaihtoehdot...

[Answer]
(a) [Equation]1850 m^2[/Equation]

(b) [Equation]\text{Noin } 29 \%.[/Equation]

[/Answer]
[/Exercise]
[/Chapter]

//Chapter with theorem and proof...........................
[Chapter header:'Chapter with theorem and proof']
[Theorem header:'Teoreeman otsikko']
Teoreeman sisältö
[/Theorem]
[Proof]
Perustelu...
[/Proof]

[Equation]
x = \begin{cases}
   a &\text{if } b \\
   c &\text{if } d
\end{cases}
[/Equation]

[Equation]\frac {(a+x)h}{2}[/Equation]
[Equation]\Omega = \omega \alpha \beta * \Sigma[/Equation]

[/Chapter]
[/CourseSection]

[/CourseNumberer]
