[CourseNumberer]
[CourseMenu]
[CourseTab header:'MAA3' /]

[CourseTab header:'osa' /]

[CourseTab header:'osa' /]

[CourseTab header:'osa' /]

[/CourseMenu]


[CourseSection]

//Chapter...........................................................
[Chapter header:'Otsikko']
Sisältö...



[/Chapter]


//Chapter with definition...........................................
[Chapter header:'Chapter with Definition']
Sisältö...

[Definition header:'MÄÄRITELMÄ: Esimerkkimääritelmä']
Määritelmän sisältö tulee tähän...
[/Definition]

[/Chapter]

//Chapter with image................................................
[Chapter header:'Chapter with Image']
[Picture imagesrc:'/img/maa3/suoraK17.png' /]
[/Chapter]

//Chapter with exercise and answer..................................
[Chapter header:'Chapter with exercise and answer']
[Exercise UID:1a9dc870-3b3e-11e9-b865-532d5d4f9c40 header:'Tehtävän otsikko' open:false]
Tehtävän ohjeistus ja vastausvaihtoehdot...

[Answer]
(a) [Equation]1850 m^2[/Equation]

(b) [Equation]\text{Noin } 29 \%.[/Equation]

[/Answer]
[/Exercise]
[/Chapter]

//Chapter with theorem and rationization...........................
[Chapter header:'Chapter with theorem and rarionalization']
[Theorem header:'Teoreeman otsikko']
Teoreeman sisältö
[/Theorem]
[Proof]
Perustelu...
[/Proof]

[Equation]
x = \begin{cases}
   a &\text{if } b \\
   c &\text{if } d
\end{cases}
[/Equation]

[Equation]\frac {(a+x)h}{2}[/Equation]
[Equation]\Omega = \omega \alpha \beta * \Sigma[/Equation]

[/Chapter]
[/CourseSection]

[/CourseNumberer]
